### PR TITLE
Adds s3 integration for CFM file upload fields.

### PR DESCRIPTION
**Pull request by chriscct7**
Needs Testing. Requires CFM pr https://github.com/chriscct7/edd-checkout-fields/pull/103

### CODE REVIEW

**Comment by pippinsplugins** [comment]
This seems to work just fine!

One issue though: I think the file should have a download link. It's not really useful if there's not a download link so it can be easily accessed.

**Comment by chriscct7** [comment]
If you have a function to backconvert it to the url. I didn't see what it was

**Comment by pippinsplugins** [comment]
You can use `get_s3_url()`

**Comment by cklosowski** [comment]
Was just coming here to mention the same thing, we should make a download link available here. I'll see if I can get that worked up and pushed.

**Comment by cklosowski** [comment]
Going to have to update both S3 and CFM. right now CFM only allows getting the attachment url downloads if the attchment id is numeric, which they are not in this case.

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 I've made a few small changes here that could use some review, allowing the S3 URLs to be parsed by CFM admin form to download them

**Comment by chriscct7** [comment]
See https://github.com/chriscct7/edd-checkout-fields/pull/103#issuecomment-248427468. Otherwise looks fine

**Pull request merged**
